#!/usr/bin/env python3
# coding=utf-8

import json
import requests
import os

# font in regolith 1.5.1
FONT = "JetBrains Mono Medium 13"

PRICE_CHANGE_PERIOD = '4h' # Available: '1h', '24h', '7d'
PRICE_CHANGE_URGENT_PERCENT = 10

API_URL = 'https://api.binance.com/api/v3/klines?symbol={}&interval={}&limit=1' # Binance API
coin = os.environ.get('BLOCK_INSTANCE', "BTCUSDT")
r = requests.get(API_URL.format(coin, PRICE_CHANGE_PERIOD))
data = json.loads(r.text)[0]

price = float(data[4]) # close
open = float(data[1])

if price > 100: precision = 0
elif price > 0.1: precision = 2
else: precision = 6

percentChange = (price - open)/open*100

percentChangeFormat = '<span color="{}" font_desc="{}"> {}{:.2f}%</span>'
valueFormat = '<span font_desc="{}">' + ' {:,.' + str(precision) + 'f}</span>'

# set color based on percent change
if percentChange > 0: percentChangeInfo = percentChangeFormat.format('#3BB92D', FONT, '▲', percentChange)
elif percentChange == 0: percentChangeInfo = percentChangeFormat.format('#CCCCCC', FONT, '', percentChange)
else: percentChangeInfo = percentChangeFormat.format('#F7555E', FONT, '▼', percentChange)

valueInfo = valueFormat.format(FONT, price)
print(valueInfo + percentChangeInfo) # Full Text
print(valueInfo) # Short Text

if percentChange > PRICE_CHANGE_URGENT_PERCENT:
    exit(33)
